// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUNzZJuio1AsTRUkyDbp7Qn7awueZ1Ziw',
    appId: '1:367758050020:web:3be006e6e1f7348755e2f1',
    messagingSenderId: '367758050020',
    projectId: 'pixamart-ffe79',
    authDomain: 'pixamart-ffe79.firebaseapp.com',
    storageBucket: 'pixamart-ffe79.appspot.com',
    measurementId: 'G-FS03RFYG0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANSwOaDENM1u-EquVmuvmvDxh2O5gvFmQ',
    appId: '1:367758050020:android:8f75ff54dafab46355e2f1',
    messagingSenderId: '367758050020',
    projectId: 'pixamart-ffe79',
    storageBucket: 'pixamart-ffe79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4-OcRDNMvL6GTfsCpsVHKO7iKI-rABig',
    appId: '1:367758050020:ios:4fc76884bc41776c55e2f1',
    messagingSenderId: '367758050020',
    projectId: 'pixamart-ffe79',
    storageBucket: 'pixamart-ffe79.appspot.com',
    iosClientId: '367758050020-lfa0n3nivqqt7sbjkr9ioh8k1p38ubfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.pixamart',
  );
}
